settings = [
    { emoji = "eyes", owner = "msawady", repo = "reacji-github-issue", labels = ["good first issue"], milestone = 1, assignees = ["msawady"], description = "## Summary \n ## Goals" },
    { emoji = "wave", owner = "msawady", repo = "reacji-github-issue" }
]