package handler

import (
	"fmt"
	"github.com/google/go-github/v45/github"
	"reacji-github-issue/config"
	"reacji-github-issue/ext_service"
)

func CreateIssueParam(setting *config.ReacjiSetting, detail *ext_service.MessageDetail) ext_service.IssueParam {
	bodyMessage := fmt.Sprintf(`
auto generated by reacji-github-issue
from: %s

%s
`, detail.Permalink, setting.Description)

	request := github.IssueRequest{
		Title: &detail.Message,
		Body:  &bodyMessage,
	}

	if len(setting.Assignees) > 0 {
		request.Assignees = &setting.Assignees
	}
	if len(setting.Labels) > 0 {
		request.Labels = &setting.Labels
	}
	if setting.Milestone > 0 {
		request.Milestone = &setting.Milestone
	}
	return ext_service.IssueParam{
		Owner:   setting.Owner,
		Repo:    setting.Repo,
		Request: request,
	}
}
