package handler

import (
	"fmt"
	"github.com/google/go-github/v45/github"
	"reacji-github-issue/config"
	"reacji-github-issue/ext_service"
)

func CreateIssueParam(setting *config.ReacjiSetting, detail *ext_service.MessageDetail) ext_service.IssueParam {
	bodyMessage := fmt.Sprintf(`
auto generated by reacji-github-issue
from: %s

%s
`, detail.Permalink, setting.Description)

	return ext_service.IssueParam{
		Owner:   setting.Owner,
		Repo:    setting.Repo,
		Request: github.IssueRequest{Title: &detail.Message, Body: &bodyMessage},
	}
}
